### PR TITLE
add gosec testing badge

### PR DESCRIPTION
**Pull request by devsecfranklin**
* Run `go mod tidy -e` 
* Add a badge for gosec testing

To use the tool to clean up the repo, run the command `gosec -conf test/.gosec.config.json -track-suppressions ./...` then remediate the findings.

### CODE REVIEW

**Comment by devsecfranklin** [comment]
Hello @JayBeale this PR is "failing correctly" now. 

Should find and tag PR when someone submits code with issues. For example:

```
[/github/workspace/peirates.go:1154] - G104 (CWE-703): Errors unhandled. (Confidence: HIGH, Severity: LOW)
    1153: 				println("Enter an IP address to scan or hit enter to exit the portscan function: ")
  > 1154: 				fmt.Scan(&input)
    1155: 				if input == "" {
```

**Comment by JayBeale** [comment]
This branch has conflicts right now.  @devsecfranklin, could you resolve these based on your intent?

**Comment by devsecfranklin** [comment]
> This branch has conflicts right now. @devsecfranklin, could you resolve these based on your intent?

The conflict is resolved. There will still be errors on every PR until we either resolve the issues the scanner is finding, or add exceptions for the ones that the scanner is triggering on.

**Comment by devsecfranklin** [comment]
All of the error handling issues have been addressed. It may make sense to create some error handling functions.

These are the outstanding issues:

```
|17:07|peirates@wolkenschloss:[peirates]> gosec -conf test/.gosec.config.json -track-suppressions ./...
[gosec] 2023/01/15 17:07:31 Including rules: default
[gosec] 2023/01/15 17:07:31 Excluding rules: default
[gosec] 2023/01/15 17:07:31 Import directory: /workspaces/peirates/cmd/peirates
[gosec] 2023/01/15 17:07:31 Import directory: /workspaces/peirates
[gosec] 2023/01/15 17:07:33 Checking package: peirates
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/attack-create-hostfs-pod.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/aws.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/commandline.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/config.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/enumerate_dns.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/exec-via-kubelet-api.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/gcp.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/http_utils.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/inject-into-pod-alpha.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/json_structs.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/kubeapi.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/kubectl_interactive.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/kubectl_wrappers.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/misc_utils.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/node_secrets.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/peirates.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/portscan.go
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/service_account_utils.go
[gosec] 2023/01/15 17:07:33 Checking package: main
[gosec] 2023/01/15 17:07:33 Checking file: /workspaces/peirates/cmd/peirates/peirates.go
Results:


[/workspaces/peirates/peirates.go:164] - G404 (CWE-338): Use of weak random number generator (math/rand instead of crypto/rand) (Confidence: MEDIUM, Severity: HIGH)
    163:        for i := range b {
  > 164:                b[i] = letters[rand.Intn(len(letters))]
    165:        }



[/workspaces/peirates/kubeapi.go:84] - G402 (CWE-295): TLS InsecureSkipVerify set true. (Confidence: HIGH, Severity: HIGH)
    83:                 // Set up our copy to ignore HTTPS errors
  > 84:                 transport.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
    85:         }



[/workspaces/peirates/http_utils.go:96] - G402 (CWE-295): TLS InsecureSkipVerify set true. (Confidence: HIGH, Severity: HIGH)
    95:                                         RootCAs:            caCertPool,
  > 96:                                         InsecureSkipVerify: ignoreTLSErrors,
    97:                                 },



[/workspaces/peirates/exec-via-kubelet-api.go:81] - G402 (CWE-295): TLS InsecureSkipVerify set true. (Confidence: HIGH, Severity: HIGH)
    80:                                                                 tr := &http.Transport{
  > 81:                                                                         TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    82:                                                                 }



[/workspaces/peirates/aws.go:265] - G402 (CWE-295): TLS InsecureSkipVerify set true. (Confidence: HIGH, Severity: HIGH)
    264:        tr := &http.Transport{
  > 265:                TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    266:        }



[/workspaces/peirates/peirates.go:766] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
    765: 
  > 766:                        if secretType != "kubernetes.io/service-account-token" {
    767:                                println("[-] This secret is not a service account token.")



[/workspaces/peirates/config.go:272] - G101 (CWE-798): Potential hardcoded credentials (Confidence: LOW, Severity: HIGH)
    271: 
  > 272:        const podVolumeSecretDir = "/volumes/kubernetes.io~secret/"
    273: 



[/workspaces/peirates/peirates.go:463] - G204 (CWE-78): Subprocess launched with variable (Confidence: HIGH, Severity: MEDIUM)
    462: 
  > 463:                                cmd := exec.Command(command, arguments...)
    464:                                out, err := cmd.CombinedOutput()



[/workspaces/peirates/inject-into-pod-alpha.go:46] - G204 (CWE-78): Subprocess launched with variable (Confidence: HIGH, Severity: MEDIUM)
    45:                         env := os.Environ()
  > 46:                         execErr := syscall.Exec(path, args, env)
    47:                         if execErr != nil {



[/workspaces/peirates/config.go:354] - G204 (CWE-78): Subprocess launched with variable (Confidence: HIGH, Severity: MEDIUM)
    353: 
  > 354:                                                        cmd := exec.Command(command, arguments...)
    355:                                                        out, err := cmd.CombinedOutput()



[/workspaces/peirates/http_utils.go:84] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    83:                 if caCertPath != "" {
  > 84:                         caCert, err := ioutil.ReadFile(caCertPath)
    85:                         if err != nil {



[/workspaces/peirates/config.go:516] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    515:                // if the etc-hosts file is there, parse it to find this pod's name
  > 516:                file, err := os.Open(etcHostPath)
    517:                if err != nil {



[/workspaces/peirates/config.go:460] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    459:                                }
  > 460:                                namespaceBytes, err := ioutil.ReadFile(namespacePath)
    461:                                if err != nil {



[/workspaces/peirates/config.go:449] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    448:                                }
  > 449:                                tokenBytes, err := ioutil.ReadFile(tokenFilePath)
    450:                                if err != nil {



[/workspaces/peirates/config.go:316] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    315:                                }
  > 316:                                namespaceBytes, err := ioutil.ReadFile(namespacePath)
    317:                                if err != nil {



[/workspaces/peirates/config.go:305] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    304:                                }
  > 305:                                tokenBytes, err := ioutil.ReadFile(tokenFilePath)
    306:                                if err != nil {



[/workspaces/peirates/config.go:203] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    202:                        }
  > 203:                        contents, err := ioutil.ReadFile(path)
    204:                        if err != nil {



[/workspaces/peirates/config.go:188] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    187:                        }
  > 188:                        contents, err := ioutil.ReadFile(path)
    189:                        if err != nil {



[/workspaces/peirates/config.go:92] - G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    91: 
  > 92:                 kubeconfigFile, err := ioutil.ReadFile(path)
    93:                 if err != nil {



[/workspaces/peirates/aws.go:135] - G107 (CWE-88): Potential HTTP request made with variable url (Confidence: MEDIUM, Severity: MEDIUM)
    134:        request := "http://169.254.169.254/latest/meta-data/iam/security-credentials/" + account
  > 135:        response2, err := http.Get(request)
    136:        if err != nil {



[/workspaces/peirates/service_account_utils.go:117] - G307 (CWE-703): Deferring unsafe method "Close" on type "*os.File" (Confidence: HIGH, Severity: MEDIUM)
    116:        }
  > 117:        defer file.Close()
    118: 



Summary:
  Gosec  : dev
  Files  : 19
  Lines  : 4424
  Nosec  : 0
  Issues : 21
```

**Comment by JayBeale** [comment]
Wow - thank you!

**Pull request merged**
